import { Task } from './types';

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Design system audit',
    description: 'Review all existing components and document inconsistencies across the product.',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2025-07-20',
    tags: ['design', 'audit'],
    createdAt: '2025-07-01',
  },
  {
    id: '2',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment to staging.',
    priority: 'high',
    status: 'todo',
    dueDate: '2025-07-22',
    tags: ['devops', 'automation'],
    createdAt: '2025-07-02',
  },
  {
    id: '3',
    title: 'Write API documentation',
    description: 'Document all REST endpoints with examples using OpenAPI specification.',
    priority: 'medium',
    status: 'todo',
    dueDate: '2025-07-25',
    tags: ['docs', 'api'],
    createdAt: '2025-07-03',
  },
  {
    id: '4',
    title: 'User research interviews',
    description: 'Conduct 5 user interviews to gather feedback on the onboarding experience.',
    priority: 'medium',
    status: 'in-progress',
    dueDate: '2025-07-18',
    tags: ['research', 'ux'],
    createdAt: '2025-07-04',
  },
  {
    id: '5',
    title: 'Refactor authentication module',
    description: 'Migrate from JWT to session-based auth and update all related tests.',
    priority: 'high',
    status: 'done',
    dueDate: '2025-07-15',
    tags: ['backend', 'security'],
    createdAt: '2025-07-01',
  },
  {
    id: '6',
    title: 'Optimize image loading',
    description: 'Implement lazy loading and WebP conversion for all product images.',
    priority: 'low',
    status: 'done',
    dueDate: '2025-07-12',
    tags: ['performance', 'frontend'],
    createdAt: '2025-07-02',
  },
  {
    id: '7',
    title: 'Set up error monitoring',
    description: 'Integrate Sentry for real-time error tracking across web and mobile.',
    priority: 'medium',
    status: 'todo',
    dueDate: '2025-07-28',
    tags: ['monitoring', 'devops'],
    createdAt: '2025-07-05',
  },
  {
    id: '8',
    title: 'Accessibility review',
    description: 'Run WCAG 2.1 AA audit and fix all critical accessibility issues found.',
    priority: 'low',
    status: 'todo',
    dueDate: '2025-07-30',
    tags: ['a11y', 'frontend'],
    createdAt: '2025-07-06',
  },
];
